# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 894c49495059d74dfa55d57d02ab70afcc66a63871e96467c890c662858483ff8d03a4b7541cc606c2d9ee98245b4daf12dc23c977562cb1e929ecc3451a2f8a

test:
  secret_key_base: 052f26b2a467cfe9c09a9f07cb302e6f4348f733de0c7ab6d21825ed40496b006a0b44c74e3d6646abe93436c39a2f905f562e1d267fa781ff04885342e8e238

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
